<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../TaskGuide.Application/TaskGuide.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" Version="*" />
    <PackageReference Include="Serilog.Sinks.File" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="*" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="*" />
  </ItemGroup>
</Project>
