<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="xunit" Version="*" />
    <PackageReference Include="xunit.runner.visualstudio" Version="*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="*" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/TaskGuide.Infrastructure/TaskGuide.Infrastructure.csproj" />
  </ItemGroup>
</Project>
